### ISSUE TITLE
Plugin bringt Homebridge zum abstürzen 

### ISSUE THREAD

**Issue by niwre2019** [lukasroegner/homebridge-store#1]
Hallo,
kannst du mir vielleicht etwas genauer ausführen, wie das Plugin genau funktioniert. Ich habe es installiert und wollte über die Kurzbefehle einen Wert speichern und wieder auslesen. Irgendetwas mache ich aber leider falsch, da die Homebridge leider immer abstürzt.
Vielen Dank

**Comment by niwre2019** [comment]
Halo,
ich habe noch ein wenig weiter getestet. Wenn ich versuche, einen Wert (POST) zu speichern, dann stürzt die gesamte Homebridge ab, wenn ich einen Wert abrufen (GET) will, dann ist das Ergebnis „none“.
Das liegt aber vermutlich daran, dass es noch keine gespeicherten Werte gibt. 
Allerdings weiß ich auch nicht, ob ich jeweils die richtige URL verwendet habe und mir ist auch nicht ganz klar, wie dieser Storage aufgebaut sein muss. Ansonsten hätte ich mal manuell einen Wert angelegt und versucht, diesen abzurufen. Irgendwie komme ich einfach nicht weiter und würde deine Hilfe benötigen.
Wäre wirklich für deine Unterstützung sehr dankbar.
Gruß Niwre

**Comment by lukasroegner** [comment]
Hi @niwre2019,

The following instructions work best with Shortcuts via "retrieve content from URL" ("Inhalt von URL abrufen"):

Let's say you want to store and retrieve some values for the variables `foo` (string) and `bar` (number). Think of a meaningful name for the collection of those variables (the PROPERTY-NAME in the API), let's use the name `settings`.

Store values:
1. Create a new shortcut action of type "retrieve content from URL"
2. Use the URL `http://<HOMEBRIDGE-IP-ADDRESS>:<STORE-API-PORT>/settings`
3. Use method `POST`
4. Add the header `Authorization` with value `<STORE-API-KEY>`
5. Set body type ("Haupttext anfordern") to `JSON`
6. Add a new field of type "text". Insert `foo` into the "key" ("Taste") field and a random value into the "text" field.
7. Add a new field of type "number". Insert `bar` into the "key" ("Taste") field and a random number into the "number" ("Zahl") field.
8. Execute the shortcut. Now, the variables for your `settings` are stores.

Retrieve values:
1. Create a new shortcut action of type "retrieve content from URL"
2. Use the URL `http://<HOMEBRIDGE-IP-ADDRESS>:<STORE-API-PORT>/settings`
3. Use method `GET`
4. Add the header `Authorization` with value `<STORE-API-KEY>`
5. Add a new shortcut action of type "retrieve dictionary value" ("Wörterbuchwert abrufen")
6. Insert `foo` into the "key" ("Schlüssel") field
7. Choose the result of the "content form URL" as source
8. Now you can use the output of the "retrieve dictionary value" action in further actions (e.g. let it print out to check its value)
9. Repeat step 5 for the other variable `foo`

If you still have issues please provide the step number at which you have problems.

**Comment by niwre2019** [comment]
Hi Lukas,
vielen Dank für die schnelle Antwort. Absolut super, jetzt funktioniert es einwandfrei, ohne deine Unterstützung hätte ich das nicht hinbekommen. Das Plugin ist eine tolle Idee, da eröffnen sich wieder ganz neue Möglichkeiten für Automationen in HomeKit.
Vielen Dank noch mal.
Gruß Niwre

**Comment by niwre2019** [comment]
Hallo Lukas,  

nochmals vielen Dank für deine Hilfe.  

Gibt es eigentlich auch die Möglichkeit, von einem anderen Linux-System (z. B. Raspi) einen Wert abzuspeichern, den ich dann wieder in einem Kurzbefehl verwenden kann? Vielleicht mit curl oder wget?  

Leider bin ich nicht so fit in diesen Dingen. Falls das möglich wäre, kannst du mir hier vielleicht auch ein kleines Beispiel zeigen, wie ich das umsetzen könnte?  

Wäre echt super nett von dir.

Viele Grüße  
Erwin  

Von: Lukas Rögner <notifications@github.com>(mailto:notifications@github.com)
Antworten: lukasroegner/homebridge-store <reply@reply.github.com>(mailto:reply@reply.github.com)
Datum: 11. Januar 2020 at 09:38:14
An: lukasroegner/homebridge-store <homebridge-store@noreply.github.com>(mailto:homebridge-store@noreply.github.com)
CC: niwre2019 <g.e.centmayer@gmail.com>(mailto:g.e.centmayer@gmail.com), Mention <mention@noreply.github.com>(mailto:mention@noreply.github.com)
Betreff: Re: [lukasroegner/homebridge-store] Plugin bringt Homebridge zum abstürzen (#1)

**Comment by lukasroegner** [comment]
HI @niwre2019,

I would recommend to play around with the software "Postman" (free). This is a tool where you can build HTTP requests and execute them. Thus, you can build up the same requests as in the example with Postman. If everything works as expected, you can use a button named "Code" on the right side of the request composer, which transforms your request into a variety of formats, including cURL.

**Comment by niwre2019** [comment]
Hi Lukas,  

vielen Dank für die Info, werde ich gleich mal testen. Irgendwie sprühen da die Ideen, wenn man mal das erste Erfolgserlebnis hatte. ;-)

Viele Grüße  
Erwin  

Von: Lukas Rögner <notifications@github.com>(mailto:notifications@github.com)
Antworten: lukasroegner/homebridge-store <reply@reply.github.com>(mailto:reply@reply.github.com)
Datum: 11. Januar 2020 at 11:14:48
An: lukasroegner/homebridge-store <homebridge-store@noreply.github.com>(mailto:homebridge-store@noreply.github.com)
CC: niwre2019 <g.e.centmayer@gmail.com>(mailto:g.e.centmayer@gmail.com), Mention <mention@noreply.github.com>(mailto:mention@noreply.github.com)
Betreff: Re: [lukasroegner/homebridge-store] Plugin bringt Homebridge zum abstürzen (#1)
