### ISSUE TITLE
Absturz bei fehlerhaften POST

### ISSUE THREAD

**Issue by niwre2019** [lukasroegner/homebridge-store#2]
Hallo,
erstmal vielen Dank für das tolle Plugin, es hat meine Homebridge wieder um einiges bereichert.
Bei einem fehlerhaften POST stürzt allerdings gleich immer die komplette Homebridge ab, könntest du das bei einem zukünftigen Update mit abfangen?
Vielen Dank.

**Comment by lukasroegner** [comment]
Hi @niwre2019,
Fixed in the latest version.

**Comment by niwre2019** [comment]
Hi Lukas,  

vielen Dank, toller Service.

Viele Grüße  
Erwin  

Von: Lukas Rögner <notifications@github.com>(mailto:notifications@github.com)
Antworten: lukasroegner/homebridge-store <reply@reply.github.com>(mailto:reply@reply.github.com)
Datum: 17. Januar 2020 at 15:30:30
An: lukasroegner/homebridge-store <homebridge-store@noreply.github.com>(mailto:homebridge-store@noreply.github.com)
CC: niwre2019 <g.e.centmayer@gmail.com>(mailto:g.e.centmayer@gmail.com), Mention <mention@noreply.github.com>(mailto:mention@noreply.github.com)
Betreff: Re: [lukasroegner/homebridge-store] Absturz bei fehlerhaften POST (#2)
